/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_h_INCLUDE
#define __map_h_INCLUDE

#define map_dataWidth 20
#define map_dataHeight 18
#define map_dataBank 0

extern const unsigned char map_data[];

#endif

/* End of MAP.H */
